options:
  port:
    type: int
    default: 80
    description: |
      NGINX listen port
  host:
    type: string
    default: 127.0.0.1
    description: listen address
  fiche-server-port:
    type: int
    default: 9999
    description: Port to run fiche on
  slug-size:
    type: int
    default: 4
    description: Slug max length
  buffer-size:
    type: int
    default: 8192
    description: Buffer size
