#!/usr/bin/env python

import amulet
import requests
import unittest

import socket


def netcat(host, port, content):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((host, int(port)))
    s.sendall(content.encode())
    s.shutdown(socket.SHUT_WR)
    while True:
        data = s.recv(4096)
        if not data:
            break
        dat = data
    s.close()
    return dat


class TestDeployment(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.deployment = amulet.Deployment(series="xenial")

        cls.deployment.add('fiche')
        cls.deployment.configure('fiche', {'fiche-server-port': 9999})
        cls.deployment.expose('fiche')

        try:
            cls.deployment.setup(timeout=900)
            cls.deployment.sentry.wait()
        except amulet.helpers.TimeoutError:
            amulet.raise_status(amulet.SKIP, msg="Environment wasn't stood up in time")
        except:
            raise
        cls.unit = cls.deployment.sentry.unit['fiche/0']
        cls.ipaddr = cls.unit.info['public-address']

    def test_1_verify_netcat(self):
        nc_resp = netcat(self.ipaddr, 9999, "test-txt")
        nc_addr = nc_resp.encode("utf-8").strip('\n')

        response = requests.get(nc_addr)
        # Check for 500
        response.raise_for_status()

        text = response.text.find('test-txt')
        found_text = text != -1

        if found_text:
            print ('Fiche is running on %s' % self.ipaddr)
        else:
            message = 'fiche is not running on %s' % self.ipaddr
            amulet.raise_status(amulet.FAIL, msg=message)


if __name__ == '__main__':
    unittest.main()
